### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by chuanjig** [PsychoinformaticsLab/pliers#412]
Hi, I try to install Pliers on a window machine (Windows 8).
I run "pip install pliers" in commandline and got no error.
However, when I run "pip install -r optional-dependencies.txt", I got the following
error message:

 Command "c:\users\chuanji\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\CHUANJI\\AppData\\Local\\Temp\\pip-install-0s1h9ubc\\blis\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\CHUANJI\AppData\Local\Temp\pip-record-sevo2hdd\install-record.txt --single-version-externally-managed --prefix C:\Users\CHUANJI\AppData\Local\Temp\pip-build-env-abiahvyg\overlay --compile" failed with error code 1 in C:\Users\CHUANJI\AppData\Local\Temp\pip-install-0s1h9ubc\blis\
  ----------------------------------------
Command "c:\users\chuanji\appdata\local\programs\python\python37-32\python.exe c:\users\chuanji\appdata\local\programs\python\python37-32\lib\site-packages\pip install --ignore-installed --no-user --prefix C:\Users\CHUANJI\AppData\Local\Temp\pip-build-env-abiahvyg\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython>=0.25 cymem>=2.0.2,<2.1.0 preshed>=3.0.2,<3.1.0 murmurhash>=0.28.0,<1.1.0 thinc==7.4.1" failed with error code 1 in None

I tried "pip install setuptools" did not solve the issue. I have no clue where this error comes from.
Thanks for any help!
Chuanji

**Comment by tyarkoni** [comment]
This looks like a problem compiling BLIS (https://github.com/flame/blis) on Windows. I'm not entirely sure what it's a dependency of, or why it's trying to compile from source (there should be a wheel). You can try `pip install blis` and see if that helps.

Note that you don't need *all* of the packages in `optional-dependencies.txt` to run pliers; that will install every package that *any* part of the library needs. So one approach here would be to not `pip install -r optional-dependencies.txt`, and just try running whatever you need to in pliers. If/when you use functionality that requires a missing library, you'll get an error with a message like "are you sure [blah] is installed?", at which point you can just install that particular dependency via pip or conda.

**Comment by chuanjig** [comment]
Hi Tal, thank you for the prompt reply. I run "pip install blis" and got an error:

 'VCINSTALLDIR': 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\'}error: [WinError 2] The system cannot find the file specified
  clang -c C:\Users\CHUANJI\AppData\Local\Temp\pip-install-xozhibpk\blis\blis\_src\config\bulldozer\bli_cntx_init_bulldozer.c -o C:\Users\CHUANJI\AppData\Local\Temp\tmpihylslnm\bli_cntx_init_bulldozer.o -O3 -std=c99 -D_POSIX_C_SOURCE=200112L -DBLIS_VERSION_STRING="0.5.1" -DBLIS_IS_BUILDING_LIBRARY -Iinclude\windows-x86_64 -I.\frame\3\ -I.\frame\ind\ukernels\ -I.\frame\1m\ -I.\frame\1f\ -I.\frame\1\ -I.\frame\include -IC:\Users\CHUANJI\AppData\Local\Temp\pip-install-xozhibpk\blis\blis\_src\include\windows-x86_64
  ----------------------------------------
Failed building wheel for blis
Running setup.py clean for blis
Failed to build blis

I tried to install Visual Studio C++ but still got the same error. There should be something wrong in my computer that
I did not catch. But I will do what you suggest now to install specific libraries when needed.
