### ISSUE TITLE
 Dockerfile: chown group error

### ISSUE THREAD

**Issue by jdkent** [PsychoinformaticsLab/pliers#413]
Docker version 19.03.12, build 48a66213fe

When building the Docker Image, I got the error (or something close to this error):
```
unable to convert uid/gid chown string to host mapping: can't find gid for group pliers: no such group
```

which occurs during [`COPY --from=builder --chown=pliers /opt/venv /opt/venv`](https://github.com/jdkent/pliers/blob/a541b07963f2d6eb45f12a52d3e6212171b03004/docker/Dockerfile#L45) because if a group is not specified in `--chown`, the version of docker I'm using assumes the group is the same as the user (e.g., `pliers`), but since [`RUN useradd --no-user-group --create-home --shell /bin/bash pliers`](https://github.com/jdkent/pliers/blob/a541b07963f2d6eb45f12a52d3e6212171b03004/docker/Dockerfile#L33) specifies that a group should not be added, then the error occurs since the `pliers` group does not exist.

I can fix it by removing the option `--no-user-group`, but I do not know what unintended side effects I'm incurring.

@kaczmarj: looks like you wrote those lines, would you know if removing `--no-user-group` is a bad idea?

**Comment by kaczmarj** [comment]
@jdkent - to my knowledge, removing `--no-user-group` should be fine. That syntax comes from neurodocker, where `--no-user-group` is added to `useradd`. I might have to take a look at that again and consider removing it... thanks for letting me know.
