### ISSUE TITLE
add cron triggered builds

### ISSUE THREAD

**Issue by jdkent** [PsychoinformaticsLab/pliers#420]
I think [adding cron triggered builds](https://docs.travis-ci.com/user/cron-jobs/) could help identify dependency weirdness sooner, rather than waiting on pull requests to identify problems.
I've been meaning to do this for a couple of my own repositories, but it seems like a good idea here too, especially if there are lulls in development, pliers shows that even less than 2 months is enough for a few packages to receive updates in a non-backwards compatible way that creates test failures.

I propose once a week for running automated builds?

**Comment by adelavega** [comment]
Good idea. Even 1-2x a month would be useful. I believe some of the tests trigger paid services which would be the only reason to not do it more often.

**Comment by adelavega** [comment]
Done! I set up a cronjob to run once a month in Travis
