### ISSUE TITLE
End-of-life for MicrosoftAPIFaceEmotionExtractor

### ISSUE THREAD

**Issue by emdupre** [PsychoinformaticsLab/pliers#470]
Following [an announcement earlier this year](https://azure.microsoft.com/en-us/blog/responsible-ai-investments-and-safeguards-for-facial-recognition/?WT.mc_id=AI-MVP-5003365), Microsoft is no longer supporting automatic inference of certain attributes (e.g. emotion, gender) with its facial recognition software. This means that the [MicrosoftAPIFaceEmotionExtractor](https://github.com/PsychoinformaticsLab/pliers/blob/9b10b27e70c3fbb7647eb1c70e031f55d824f3f6/pliers/extractors/api/microsoft.py#L105-L119) is no longer functional and now returns `Exception: Invalid request has been sent.` when calling with `pliers` 0.4.1.

It would be helpful to remove this class from the code base and docs to make it clear that this analysis is no longer possible !

**Comment by adelavega** [comment]
Thank you! I agree. Again, the darn API extractors are such a moving target.
