### ISSUE TITLE
Allow for non-English transcription with Rev.AI

### ISSUE THREAD

**Issue by emdupre** [PsychoinformaticsLab/pliers#479]
Currently, it's not obvious how to request languages other than English when using the `RevAISpeechAPIConverter`. From [their docs](https://docs.rev.ai/api/asynchronous/reference/#operation/SubmitTranscriptionJob!ct=application/json&path=language&t=request) it's clear that requests can include a number of languages (including French, which is my use case !), but it's not obvious how to add that param in a pliers call.

From my understanding, [the transcription option will not automatically infer the language](https://docs.rev.ai/resources/tutorials/transcribe-audio-automatic-language-identification/#technical-approach); instead, that should be supplied by the user or done in a first-pass language identification step.

I believe `RevAISpeechAPIConverter` would need to accept a new `language` parameter that could then be passed here:
https://github.com/PsychoinformaticsLab/pliers/blob/9b10b27e70c3fbb7647eb1c70e031f55d824f3f6/pliers/converters/api/revai.py#L73-L77

Does that sound approximately correct / Would that be of interest ?

**Comment by adelavega** [comment]
Looks like an enhanceement.... @qmac what do you think?

**Comment by emdupre** [comment]
Just following up on this ! Let me know if this is a welcome addition, and I'd be happy to add it.

**Comment by adelavega** [comment]
It looks good to me, and I'm inferring from @qmac's reaction (he works for Rev ;) that it makes sense.

**Comment by qmac** [comment]
Yep! I think your suggestion is all that's needed! You'll need version >= 2.11.0 of the python sdk too.
