### ISSUE TITLE
Remove Indico from examples

### ISSUE THREAD

**Issue by emdupre** [PsychoinformaticsLab/pliers#480]
Following up on https://github.com/PsychoinformaticsLab/pliers/pull/369, it looks like Indico is still included in several of the examples [here](http://psychoinformaticslab.github.io/pliers/graphs.html?highlight=indicoapitextextractor#listing-1) and in [this notebook](https://github.com/PsychoinformaticsLab/pliers/blob/9b10b27e70c3fbb7647eb1c70e031f55d824f3f6/examples/Vision%20APIs.ipynb).

It would make sense to remove these, given that Indico is no longer accessible through a public API !

**Comment by adelavega** [comment]
Thanks for the catch

**Comment by adelavega** [comment]
Done!
